captive_portal/admin_backup/base/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('user.urls', namespace='user')),
    path('captive-portal/', include('captive_portal.urls', namespace='captive_portal')),
    path('configuration/', include('configuration.urls', namespace='configuration')),
    path('clients-live-traffic/', include('clients_live_traffic.urls', namespace='clients_live_traffic')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

captive_portal/admin_backup/captive_portal/urls.py
from django.urls import path
from captive_portal import views
from django.contrib.auth.context_processors import auth


app_name = 'captive_portal'

urlpatterns = [
    path('', views.CaptivePortalOverview.as_view(), name='overview'),

    path('settings', views.Settings.as_view(), name='settings'),

    path('vouchers', views.VoucherList.as_view(), name='voucher-list'),
    path('vouchers/create', views.VoucherCreate.as_view(), name='voucher-create'),
    path('voucher/edit/<str:pk>', views.VoucherEdit.as_view(), name='voucher-edit'),
    path('voucher/delete/<str:pk>', views.VoucherDelete.as_view(), name='voucher-delete'),

    path('package/create', views.PackageCreate.as_view(), name='package-create'),
    path('package/edit/<str:pk>', views.PackageEdit.as_view(), name='package-edit'),
    path('package/delete/<str:pk>', views.PackageDelete.as_view(), name='package-delete'),

]

captive_portal/admin_backup/configuration/urls.py
from django.urls import path
from configuration import views

app_name = 'configuration'

urlpatterns = [
    path('user/create', views.UserCreate.as_view(), name='user-create'),
    path('user/list', views.UserList.as_view(), name='user-list'),
    path('user/edit/<str:pk>', views.UserEdit.as_view(), name='user-edit'),
    path('user/delete/<str:pk>', views.UserDelete.as_view(), name='user-delete'),

    path('role/create', views.RoleCreate.as_view(), name='role-create'),
    path('role/edit/<str:pk>', views.RoleEdit.as_view(), name='role-edit'),
    path('role/delete/<str:pk>', views.RoleDelete.as_view(), name='role-delete'),
    path('role/list', views.RoleList.as_view(), name='role-list'),

]

captive_portal/admin_backup/dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.Dashboard.as_view(), name='home'),
]

captive_portal/admin_backup/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('login', views.UserLogin.as_view(), name='login'),
    path('logout', views.UserLogout.as_view(), name='logout'),
]

captive_portal/admin_backup/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Analytics Portal - {% block title %} {% endblock title %}</title>

    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
	<link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">

    <link href="{% static 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <style>
        a{
            cursor: pointer;
        }
    </style>

     {% block head_css %} {% endblock head_css %}
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
          {% include 'sidebar.html' %}

          {% include 'top_nav.html' %}

          <div class="right_col" role="main">

              {% include 'messages.html' %}

              {% block content %} {% endblock content %}

          </div>

          </div>
      </div>
    </div>

    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
    <script src="{% static 'vendors/skycons/skycons.js' %}"></script>
    <script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
    <script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
    <script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
    <script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
    <script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
    <script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
    <script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
    <script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
    <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'vendors/validator/validator.js' %}"></script>

    <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <script src="{% static 'build/js/custom.min.js' %}"></script>

    {% block extra_js %} {% endblock extra_js %}

    <script>
        $(document).ready(function() {
            $('table').DataTable({
                "iDisplayLength": 5
            });
        } );
    </script>
	
  </body>
</html>

captive_portal/admin_backup/templates/messages.html
{% if messages %}
    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-left: 0; padding-right: 0">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            {{ message }}
        </div>
        {% endfor %}
    </div>

{% endif %}

captive_portal/admin_backup/templates/sidebar.html
{% load static %}

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'dashboard:home' %}" class="site_title">
                  <i class="fa fa-paw"></i> <span>Analytics Portal</span>
              </a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <img src="{% static 'img/img.jpg' %}" alt="..." class="img-circle profile_img">
          </div>
          <div class="profile_info">
            <span>Welcome, <strong>{{ request.user.username }}</strong></span>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <ul class="nav side-menu">

              {% if perms.dashboard %}
                  <li>
                      <a href="{% url 'dashboard:home' %}">
                          <i class="fa fa-bar-chart"></i> Dashboard
                      </a>
                  </li>
              {% endif %}

              {% if perms.VoucherList or perms.Settings or perms.CaptivePortalOverview %}
                <li>
                  <a>
                      <i class="fa fa-wrench"></i>
                      Captive Portal <span class="fa fa-chevron-down"></span>
                  </a>
                  <ul class="nav child_menu">
                      {% if perms.CaptivePortalOverview %}
                        <li><a href="{% url 'captive_portal:overview' %}">Overview</a></li>
                      {% endif %}

                      {% if perms.Settings %}
                        <li><a href="{% url 'captive_portal:settings' %}">Settings</a></li>
                      {% endif %}

                      {% if perms.VoucherList %}
                        <li><a href="{% url 'captive_portal:voucher-list' %}">Voucher Management</a></li>
                      {% endif %}
                  </ul>
              </li>
              {% endif %}

              <li>
                  <a>
                      <i class="fa fa-signal"></i>
                      Clients Live Traffic <span class="fa fa-chevron-down"></span>
                  </a>
                  <ul class="nav child_menu">
                      <li><a href="{% url 'clients_live_traffic:wifi_clients_data' %}">WIFI Clients Data</a></li>
                      <li><a href="#">Kontakt Data</a></li>
                  </ul>
              </li>

              <li>
                  <a><i class="fa fa-desktop"></i> Content Delivery Portal </a>
              </li>

              <li>
                  <a>
                      <i class="fa fa-line-chart"></i>
                      Retail Reports <span class="fa fa-chevron-down"></span>
                  </a>
                  <ul class="nav child_menu">
                      <li><a href="#">Traffic Reports (Zone)</a></li>
                      <li><a href="#">Traffic Reports (Place)</a></li>
                      <li><a href="#">Traffic Reports (Criteria Base)</a></li>
                      <li><a href="#">User Reports</a></li>
                      <li><a href="#">Device Reports</a></li>
                  </ul>
              </li>

              {% if perms.RoleList or perms.UserList %}
                <li>
                  <a>
                      <i class="fa fa-gears"></i>
                      Configuration <span class="fa fa-chevron-down"></span>
                  </a>
                  <ul class="nav child_menu">
                      {% if perms.RoleList %}
                        <li><a href="{% url 'configuration:role-list' %}">Roles</a></li>
                      {% endif %}

                      {% if perms.UserList %}
                      <li><a href="{% url 'configuration:user-list' %}">Users</a></li>
                      {% endif %}

                  </ul>
              </li>
              {% endif %}

            </ul>
          </div>
        </div>

    </div>
</div>

captive_portal/admin_backup/templates/top_nav.html
{% load static %}


<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/img.jpg' %}" alt="">
            {{ request.user.username }}
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile </a></li>
            <li><a href="{% url 'user:logout' %}"> Log Out</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>