captive_portal/admin_backup/base/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('user.urls', namespace='user')),
    path('captive-portal/', include('captive_portal.urls', namespace='captive_portal')),
    path('configuration/', include('configuration.urls', namespace='configuration')),
    path('clients-live-traffic/', include('clients_live_traffic.urls', namespace='clients_live_traffic')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

captive_portal/admin_backup/configuration/urls.py
from django.urls import path
from configuration import views

app_name = 'configuration'

urlpatterns = [
    path('user/create', views.UserCreate.as_view(), name='user-create'),
    path('user/list', views.UserList.as_view(), name='user-list'),
    path('user/edit/<str:pk>', views.UserEdit.as_view(), name='user-edit'),
    path('user/delete/<str:pk>', views.UserDelete.as_view(), name='user-delete'),

    path('role/create', views.RoleCreate.as_view(), name='role-create'),
    path('role/edit/<str:pk>', views.RoleEdit.as_view(), name='role-edit'),
    path('role/delete/<str:pk>', views.RoleDelete.as_view(), name='role-delete'),
    path('role/list', views.RoleList.as_view(), name='role-list'),

]

captive_portal/admin_backup/configuration/models.py
from mongoengine import fields, Document, CASCADE
from django.contrib.auth.hashers import check_password, make_password
from django.contrib import auth
from django.conf import settings
from django.contrib.auth.models import _user_has_perm


class Permission(Document):
    name = fields.StringField(required=True)

    def __unicode__(self):
        return self.name

    meta = {
        'indexes': [
            {'fields': ['name'], 'unique': True}
        ]
    }


class Role(Document):
    name = fields.StringField(unique=True, required=True)

    def __unicode__(self):
        return self.name

    meta = {
        'indexes': [
            {'fields': ['name']}
        ]
    }


class RolePermission(Document):
    role = fields.ReferenceField(Role, required=True, reverse_delete_rule=CASCADE)
    permission = fields.ReferenceField(Permission, required=True, reverse_delete_rule=CASCADE)

    meta = {
        'indexes': [
            {'fields': ['role', 'permission']}
        ]
    }


class User(Document):
    first_name = fields.StringField(max_length=30, required=False)
    last_name = fields.StringField(max_length=30, required=False)
    username = fields.StringField(max_length=30, required=False)
    email = fields.EmailField(max_length=30, required=False)
    password = fields.StringField(min_length=6, max_length=128, required=False)
    phone = fields.StringField(max_length=15, required=False)

    # Designates that this user has all permissions without explicitly assigning them.
    is_superuser = fields.BooleanField(default=False)

    USERNAME_FIELD = getattr(settings, 'USERNAME_FIELD', 'username')

    meta = {
        'indexes': [
            {'fields': ['username', 'email']}
        ]
    }

    def __unicode__(self):
        return self.username if self.username else self.email

    def save(self, *args, **kwargs):
        if not self.id:
            self.set_password(self.password)
        return super().save(*args, **kwargs)

    @property
    def full_name(self):
        return '{}{}'.format(self.first_name, self.last_name)

    @property
    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True

    def set_password(self, raw_password):
        self.password = make_password(raw_password)
        return self

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    def get_role_permissions(self, obj=None):
        """
        Returns a list of permission strings that this user has through his/her
        roles. This method queries all available auth backends. If an object
        is passed in, only permissions matching this object are returned.
        """
        permissions = set()
        for backend in auth.get_backends():
            if hasattr(backend, "get_role_permissions"):
                permissions.update(backend.get_role_permissions(self, obj))
        return permissions

    def get_all_permissions(self, obj=None):
        """
        Returns a list of permission strings that this user has through his/her
        roles. This method queries all available auth backends. If an object
        is passed in, only permissions matching this object are returned.
        """
        permissions = set()
        for backend in auth.get_backends():
            print(backend.__dict__)
            if hasattr(backend, "get_role_permissions"):
                permissions.update(backend.get_role_permissions(self, obj))
        return permissions

    def has_perm(self, perm, obj=None):
        """
        Returns True if the user has the specified permission. This method
        queries all available auth backends, but returns immediately if any
        backend returns True. Thus, a user who has permission from a single
        auth backend is assumed to have permission in general. If an object is
        provided, permissions for this specific object are checked.
        """
        # superusers have all permissions.
        if self.is_superuser:
            return True

        return _user_has_perm(self, perm, obj)

    def has_perms(self, perm_list, obj=None):
        """
        Returns True if the user has each of the specified permissions. If
        object is passed, it checks if the user has all required perms for this
        object.
        """
        for perm in perm_list:
            if not self.has_perm(perm, obj):
                return False
        return True

    @property
    def is_anonymous(self):
        """
        Always return False. This is a way of comparing User objects to
        anonymous users.
        """
        return False


class UserRole(Document):
    role = fields.ReferenceField(Role, required=True, reverse_delete_rule=CASCADE)
    user = fields.ReferenceField(User, required=True, reverse_delete_rule=CASCADE)

    meta = {
        'indexes': [
            {'fields': ['role', 'user']}
        ]
    }


class SocialProvider(Document):
    """
    This table keep settings for social providers for which this application would
    allow login for user.
    Admin can add/remove social providers from here to decide which social login
    to keep and which one to remove
    """
    name = fields.StringField(required=True)
    admin_email = fields.EmailField(required=True)

    """
    This field could save different type of values depends on provider
    it could be client_id and client_secret
    or it could be API_KEY or any other oAuth2.0 credentials of social site
    """
    configuration = fields.DictField(required=True)
    is_active = fields.BooleanField(default=True)

    def __unicode__(self):
        return '{} {}'.format(self.name, self.configuration)

    meta = {
        'indexes': [
            {'fields': ['name']}
        ]
    }

captive_portal/admin_backup/configuration/forms.py
from mongodbforms import DocumentForm
from django import forms
from bson import ObjectId
from configuration import models


class UserCreateForm(DocumentForm):

    username = forms.CharField(required=True)
    password = forms.CharField(required=True)
    roles = forms.MultipleChoiceField(
        choices=[(str(role.id), role.name) for role in models.Role.objects.all()]
    )

    class Meta:
        document = models.User
        fields = ['first_name', 'last_name', 'username', 'password', 'email', 'roles']

    def save(self):
        user = super().save(commit=True)
        roles = [ObjectId(role_id) for role_id in self.cleaned_data.get('roles')]
        for role in roles:
            models.UserRole.objects.create(role=role, user=user)
        return user

    def clean_roles(self):
        roles = self.cleaned_data.get('roles')
        if not roles:
            self.add_error('roles', 'This field is required')
        return roles


class UserEditForm(DocumentForm):
    roles = forms.MultipleChoiceField(
        choices=[(str(role.id), role.name) for role in models.Role.objects.all()]
    )

    class Meta:
        document = models.User
        fields = ['first_name', 'last_name', 'email', 'roles']

    def save(self):
        user = super().save(commit=True)
        roles = [ObjectId(role_id) for role_id in self.cleaned_data.get('roles')]
        models.UserRole.objects.filter(user=user.to_dbref()).delete()
        for role in roles:
            models.UserRole.objects.create(user=user.to_dbref(), role=role)

        return user


class RoleCreateForm(DocumentForm):
    name = forms.CharField(required=True)
    permissions = forms.MultipleChoiceField(
        choices=[(str(perm.id), perm.name) for perm in models.Permission.objects.all()]
    )

    class Meta:
        document = models.Role
        fields = ['name', 'permissions']

    def save(self):
        role = super().save(commit=True)
        permissions = [ObjectId(perm_id) for perm_id in self.cleaned_data.get('permissions')]
        for perm in permissions:
            models.RolePermission.objects.create(role=role.to_dbref(), permission=perm)

        return role

    def clean_permissions(self):
        permissions = self.cleaned_data.get('permissions')
        if not permissions:
            self.add_error('permissions', 'This field is required')
        return permissions


class RoleEditForm(DocumentForm):
    permissions = forms.MultipleChoiceField(
        choices=[(str(perm.id), perm.name) for perm in models.Permission.objects.all()]
    )

    class Meta:
        document = models.Role
        fields = ['name', 'permissions']

    def save(self):
        role = super().save(commit=True)
        permissions = [ObjectId(perm_id) for perm_id in self.cleaned_data.get('permissions')]
        models.RolePermission.objects.filter(role=role.to_dbref()).delete()
        for perm in permissions:
            models.RolePermission.objects.create(role=role.to_dbref(), permission=perm)

        return role

captive_portal/admin_backup/configuration/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from configuration import forms
from configuration import models


class RoleCreate(PermissionRequiredMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'configuration/role_create.html'
    form_class = forms.RoleCreateForm
    queryset = models.Role.objects.all()
    success_url = reverse_lazy('configuration:role-list')
    success_message = 'Role added successfully'
    permission_required = ('RoleCreate',)
    raise_exception = True


class RoleEdit(PermissionRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    template_name = 'configuration/role_edit.html'
    form_class = forms.RoleEditForm
    queryset = models.Role.objects.all()
    success_url = reverse_lazy('configuration:role-list')
    success_message = 'Role updated successfully.'
    permission_required = ('RoleEdit',)
    raise_exception = True

    def get_context_data(self, **kwargs):
        role = self.get_object()
        kwargs = super().get_context_data(**kwargs)
        role_permissions = models.RolePermission.objects.filter(role=role.to_dbref())
        kwargs.get('form').fields['permissions'].initial = [str(perm.permission.id) for perm in role_permissions]
        return kwargs


class RoleList(PermissionRequiredMixin, generic.ListView):
    template_name = 'configuration/role_list.html'
    queryset = models.Role.objects.all()
    context_object_name = 'roles'
    permission_required = ('RoleList',)
    raise_exception = True

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(*args, **kwargs)
        roles = []
        for role in kwargs.get('roles'):
            r = {
                'id': role.id,
                'name': role.name,
                'permissions': [perm.permission.name for perm in models.RolePermission.objects.filter(role=role.to_dbref())]
            }
            roles.append(r)

        kwargs['roles'] = roles
        return kwargs


class RoleDelete(PermissionRequiredMixin, generic.DeleteView):
    queryset = models.Role.objects.all()
    success_url = reverse_lazy('configuration:role-list')
    success_message = 'Role deleted successfully.'
    permission_required = ('RoleDelete',)
    raise_exception = True

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        return response


class UserCreate(PermissionRequiredMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'configuration/user_create.html'
    form_class = forms.UserCreateForm
    queryset = models.User.objects.all()
    success_url = reverse_lazy('configuration:user-list')
    success_message = 'User added successfully'
    permission_required = ('UserCreate',)
    raise_exception = True


class UserList(PermissionRequiredMixin, generic.ListView):
    template_name = 'configuration/user_list.html'
    queryset = models.User.objects.filter(is_superuser=False)
    context_object_name = 'users'
    permission_required = ('UserList',)
    raise_exception = True

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(*args, **kwargs)
        users = []
        for user in kwargs.get('users'):
            r = {
                'id': user.id,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'username': user.username,
                'roles': [user_role.role.name for user_role in models.UserRole.objects.filter(user=user.to_dbref())]
            }
            users.append(r)

        kwargs['users'] = users
        return kwargs


class UserEdit(PermissionRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    template_name = 'configuration/user_edit.html'
    form_class = forms.UserEditForm
    queryset = models.User.objects.all()
    success_url = reverse_lazy('configuration:user-list')
    success_message = 'User updated successfully.'
    permission_required = ('UserEdit',)
    raise_exception = True

    def get_context_data(self, **kwargs):
        user = self.get_object()
        kwargs = super().get_context_data(**kwargs)
        user_roles = models.UserRole.objects.filter(user=user.to_dbref())
        kwargs.get('form').fields['roles'].initial = [str(user_role.role.id) for user_role in user_roles]
        return kwargs


class UserDelete(PermissionRequiredMixin, generic.DeleteView):
    queryset = models.User.objects.all()
    success_url = reverse_lazy('configuration:user-list')
    success_message = 'User deleted successfully.'
    permission_required = ('UserDelete',)
    raise_exception = True

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        return response

captive_portal/admin_backup/templates/configuration/role_create.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Create Role</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="name" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.name.value != None %} value="{{ form.name.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.name.errors }}</div>
                  </div>


                 <div class="item form-group {% if form.permissions.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Permissions</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <select style="min-height: 300px" multiple name="{{ form.permissions.name }}" class="form-control col-md-7 col-xs-12">
                        {% for choice in form.permissions.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <div class="alert">{{ form.permissions.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Create</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin_backup/templates/configuration/role_edit.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Edit Role Permissions</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="name" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.name.value != None %} value="{{ form.name.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.name.errors }}</div>
                  </div>

                 <div class="item form-group {% if form.permissions.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Permissions</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <select style="min-height: 300px" multiple name="{{ form.permissions.name }}" class="form-control col-md-7 col-xs-12">
                        {% for choice in form.permissions.field.choices %}
                            <option {% if choice.0 in form.permissions.initial %} selected="selected" {% endif %} value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <div class="alert">{{ form.permissions.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Update</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin_backup/templates/configuration/role_list.html
{% extends 'base.html' %}

{% block content %}

   <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Roles</h2>

            {% if perms.UserCreate %}
                <a href="{% url 'configuration:role-create' %}" role="button" class="btn btn-info btn-xs pull-right">
                    Add Role
                </a>
            {% endif %}
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table  class="table jambo_table">
              <thead>
                <tr>
                  <th>Role</th>
                  <th>Permissions</th>
                  <th></th>
                </tr>
              </thead>


              <tbody>
                {% for role in roles %}
                    <tr>
                      <td>{{ role.name }}</td>
                      <td>
                          <ul>
                              {% for perm in role.permissions %}
                                <li>{{ perm }}</li>
                              {% endfor %}
                          </ul>
                      </td>
                      <td>
                          {% if perms.RoleEdit %}
                          <a href="{% url 'configuration:role-edit' role.id %}" title="Edit"><i class="fa fa-edit"></i> </a>
                          {% endif %}

                          {% if perms.RoleDelete %}
                              <a title="Delete" class="delete-role" ><i class="fa fa-trash"></i></a>
                              <form style="display: none;" method="post" action="{% url 'configuration:role-delete' role.id %}">
                                {% csrf_token %}
                              </form>
                          {% endif %}
                      </td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>

   </div>

{% endblock content %}


{% block extra_js %}
    <script>
        $(document).ready(function(){
            $('a.delete-role').on('click', function(){
                if (confirm('Do you really want to delete?')){
                    $(this).next().submit();
                }

            });
        });
    </script>
{% endblock extra_js %}

captive_portal/admin_backup/templates/configuration/user_create.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Create User</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.first_name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">First Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="first_name" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.first_name.value != None %} value="{{ form.first_name.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.first_name.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.last_name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Last Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="last_name" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.last_name.value != None %} value="{{ form.last_name.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.last_name.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.username.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Username</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="username" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.username.value != None %} value="{{ form.username.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.username.errors }}</div>
                  </div>

                 <div class="item form-group {% if form.password.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Password</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="password" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.password.value != None %} value="{{ form.password.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.password.errors }}</div>
                  </div>

                 <div class="item form-group {% if form.roles.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Role</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <select style="min-height: 150px" multiple name="{{ form.roles.name }}" class="form-control col-md-7 col-xs-12">
                        {% for choice in form.roles.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <div class="alert">{{ form.roles.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Create</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin_backup/templates/configuration/user_list.html
{% extends 'base.html' %}

{% block content %}

   <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>User List</h2>

             {% if perms.UserCreate %}
            <a href="{% url 'configuration:user-create' %}" role="button" class="btn btn-info btn-xs pull-right">
                Add User
            </a>
            {% endif %}
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table  class="table jambo_table">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Username</th>
                  <th>Roles</th>
                  <th></th>
                </tr>
              </thead>


              <tbody>
                {% for user in users %}
                    <tr>
                      <td>{{ user.first_name }}</td>
                      <td>{{ user.last_name }}</td>
                      <td>{{ user.username }}</td>
                      <td>
                          <ul>
                              {% for role in user.roles %}
                                <li>{{ role }}</li>
                              {% endfor %}
                          </ul>
                      </td>
                      <td>
                          {% if perms.UserCreate %}
                          <a href="{% url 'configuration:user-edit' user.id %}" title="Edit"><i class="fa fa-edit"></i> </a>
                          {% endif %}&emsp;

                          {% if perms.UserDelete %}
                              <a title="Delete" class="delete-user" ><i class="fa fa-trash"></i></a>
                              <form style="display: none;" method="post" action="{% url 'configuration:user-delete' user.id %}">
                                {% csrf_token %}
                              </form>
                          {% endif %}
                      </td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>

   </div>

{% endblock content %}


{% block extra_js %}
    <script>
        $(document).ready(function(){
            $('a.delete-user').on('click', function(){
                if (confirm('Do you really want to delete?')){
                    $(this).next().submit();
                }

            });
        });
    </script>
{% endblock extra_js %}