captive_portal/admin/api/base/urls.py
import os
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_swagger.views import get_swagger_view

urlpatterns = [
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('captive-portal/', include('captive_portal.urls', namespace='captive_portal')),
    path('configuration/', include('configuration.urls', namespace='configuration')),
    path('clients-live-traffic/', include('clients_live_traffic.urls', namespace='clients_live_traffic')),
    path('user/', include('user.urls', namespace='user')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

baseUrl = '/'

if os.environ['DJANGO_SETTINGS_MODULE'] == 'base.settings.staging':
    baseUrl = '/captive-portal-admin-api/'

schema_view = get_swagger_view(
    title='Captive Portal Admin API', patterns=urlpatterns, url=baseUrl)

urlpatterns += [path('', schema_view)]

captive_portal/admin/api/captive_portal/urls.py
from django.urls import path
from captive_portal import views


app_name = 'captive_portal'

urlpatterns = [
    path('overview', views.CaptivePortalOverview.as_view(), name='overview'),
    path('update-settings', views.UpdateSettings.as_view(), name='update-settings'),
    path('social-provider/list', views.ProviderList.as_view(), name='social-provider-list'),
    path('allowed-social-login', views.AllowedSocialLogin.as_view(), name='allowed-social-login'),

    path('voucher/list', views.VoucherList.as_view(), name='voucher-list'),
    path('voucher/create', views.VoucherCreate.as_view(), name='voucher-create'),
    path('voucher/edit/<str:id>', views.VoucherEdit.as_view(), name='voucher-edit'),
    path('voucher/delete/<str:id>', views.VoucherDelete.as_view(), name='voucher-delete'),

    path('package/list', views.PackageList.as_view(), name='package-list'),
    path('package/create', views.PackageCreate.as_view(), name='package-create'),
    path('package/edit/<str:id>', views.PackageEdit.as_view(), name='package-edit'),
    path('package/delete/<str:id>', views.PackageDelete.as_view(), name='package-delete'),

]

captive_portal/admin/api/captive_portal/models.py
from mongoengine import fields, Document, DynamicDocument, CASCADE
from django.utils import timezone
from django.conf import settings
from configuration.models import User, Device


class Settings(Document):
    # in minutes
    login_timeout = fields.IntField(min_value=1, default=1, required=True)


class Package(Document):
    name = fields.StringField(required=True)
    data_limit = fields.StringField(required=True)
    activation_days = fields.IntField(min_value=1, required=True)
    expiration_days = fields.IntField(min_value=1, required=True)

    def __unicode__(self):
        return self.name if self.name else 'N/A'


class Voucher(Document):
    STATUS_CHOICES = (
        ('purchased', 'Purchased'),
        ('active', 'Active'),
        ('expired', 'Expired'),
        ('disabled', 'Disabled'),
        ('fullfilled', 'Fullfilled')
    )
    name = fields.StringField(required=True)
    code = fields.StringField(required=True)
    creation_date = fields.DateTimeField(default=timezone.now)
    expiration_date = fields.DateTimeField(default=timezone.now)
    activation_date = fields.DateTimeField(default=timezone.now)
    activation_expiration_date = fields.DateTimeField(default=timezone.now)
    # in GBs
    data_limit = fields.IntField(min_value=1)
    status = fields.StringField(choices=STATUS_CHOICES)
    total_data_usage = fields.StringField()

    package = fields.ReferenceField(Package, reverse_delete_rule=CASCADE, required=True)


class SessionHistory(Document):
    start_datetime = fields.DateTimeField(default=timezone.now)
    end_datetime = fields.DateTimeField(default=timezone.now)
    data_usage = fields.StringField()
    voucher = fields.ReferenceField(Voucher, reverse_delete_rule=CASCADE)
    device = fields.ReferenceField(Device, reverse_delete_rule=CASCADE)
    user = fields.ReferenceField(User, reverse_delete_rule=CASCADE)


class WifiUser(DynamicDocument):
    """
    These are Collections for existing database just to read data from WIFI Database
    """
    meta = {
        'db_alias': settings.WIFI_DB_ALIAS,
        'collection': 'client',
    }


class WifiGuest(DynamicDocument):
    meta = {
        'db_alias': settings.WIFI_DB_ALIAS,
        'collection': 'guest',
    }

captive_portal/admin/api/captive_portal/forms.py
from mongodbforms import DocumentForm
from django import forms
from captive_portal import models


class AllowedSocialLoginForm(forms.Form):
    id = forms.CharField(widget=forms.HiddenInput())
    name = forms.CharField(required=False)
    is_active = forms.BooleanField(required=False)

    class Meta:
        fields = ['id', 'name', 'is_active']


class WifiLoginTimeoutForm(DocumentForm):

    class Meta:
        document = models.Settings
        fields = ['login_timeout']


class PackageForm(DocumentForm):
    class Meta:
        document = models.Package
        fields = ['name', 'data_limit', 'activation_days', 'expiration_days']


class VoucherForm(DocumentForm):

    class Meta:
        document = models.Voucher
        fields = ['name', 'code', 'package']

captive_portal/admin/api/captive_portal/views.py
from rest_framework_mongoengine import generics
from rest_framework.response import Response
from functools import reduce
from base.utils import convert_size
from captive_portal import serializers
from captive_portal import models
from configuration.models import Provider
from bson import ObjectId


class CaptivePortalOverview(generics.GenericAPIView):
    http_method_names = ['get']

    @staticmethod
    def get(request):
        data = dict()
        data['users_count'] = models.WifiUser.objects.count()
        data['guests_count'] = models.WifiGuest.objects.count()
        active_guests = models.WifiGuest.objects.filter(is_valid=True)
        # aggregate i.e sum() doesn't work in MongoDB 2.0, so traverse each record and sum it
        data_usage = reduce(
            lambda s, guest: s + guest.downloadTotal + guest.uploadTotal,
            active_guests, 0
        )
        data['data_usage'] = convert_size(data_usage)
        return Response(data)


class UpdateSettings(generics.UpdateAPIView):

    serializer_class = serializers.SettingsSerializer
    queryset = models.Settings.objects.all()
    object = None
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        return self.put(request, *args, **kwargs)

    @staticmethod
    def get_object():
        if models.Settings.objects.count() < 1:
            return models.Settings.objects.create()

        return models.Settings.objects.first()


class ProviderList(generics.ListAPIView):
    serializer_class = serializers.ProviderSerializer
    queryset = Provider.objects.all()


class AllowedSocialLogin(generics.GenericAPIView):
    serializer_class = serializers.AllowedSocialLoginSerializer
    queryset = Provider.objects.all()
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)


class VoucherList(generics.ListAPIView):
    serializer_class = serializers.VoucherSerializer
    queryset = models.Voucher.objects.all()


class VoucherCreate(generics.CreateAPIView):
    model = models.Voucher
    serializer_class = serializers.VoucherSerializer


class VoucherEdit(generics.UpdateAPIView):
    queryset = models.Voucher.objects.all()
    serializer_class = serializers.VoucherSerializer
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        try:
            ObjectId(kwargs.get('id'))
        except:
            return Response({'detail': 'invalid voucher id'})
        return self.patch(request, *args, **kwargs)


class VoucherDelete(generics.RetrieveDestroyAPIView):
    queryset = models.Voucher.objects.all()
    serializer_class = serializers.VoucherSerializer
    http_method_names = ['post']

    def get_object(self):
        return models.Voucher.objects.get(id=ObjectId(self.kwargs.get('id')))

    def post(self, request, *args, **kwargs):
        try:
            ObjectId(kwargs.get('id'))
        except:
            return Response({'detail': 'invalid voucher id'})
        return self.delete(request, *args, **kwargs)


class PackageList(generics.ListAPIView):
    queryset = models.Package.objects.all()
    serializer_class = serializers.PackageSerializer


class PackageCreate(generics.CreateAPIView):
    model = models.Package
    serializer_class = serializers.PackageSerializer


class PackageEdit(generics.UpdateAPIView):
    queryset = models.Package.objects.all()
    serializer_class = serializers.PackageSerializer
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        try:
            ObjectId(kwargs.get('id'))
        except:
            return Response({'detail': 'invalid package id'})
        return self.patch(request, *args, **kwargs)


class PackageDelete(generics.RetrieveDestroyAPIView):
    queryset = models.Package.objects.all()
    serializer_class = serializers.PackageSerializer
    http_method_names = ['post']

    def get_object(self):
        return models.Package.objects.get(id=ObjectId(self.kwargs.get('id')))

    def post(self, request, *args, **kwargs):
        try:
            ObjectId(kwargs.get('id'))
        except:
            return Response({'detail': 'invalid package id'})
        return self.delete(request, *args, **kwargs)

captive_portal/admin/api/templates/captive_portal/overview.html
{% extends 'base.html' %}

{% block content %}

    <div>
      <div class="row top_tiles">
         <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
              <div class="tile-stats">
                  <div class="icon"><i class="fa fa-graduation-cap"></i></div>
                  <div class="count">{{ users_count }}</div>
                  <h3>Users</h3>
                  <p><a href="javascript:;">More Info</a> </p>
                </div>
              </div>
         <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
              <div class="tile-stats">
                  <div class="icon"><i class="fa fa-user"></i></div>
                  <div class="count">{{ guests_count }}</div>
                  <h3>Guests</h3>
                  <p><a href="javascript:;">More Info</a> </p>
                </div>
         </div>

          <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-wifi"></i></div>
                  <div class="count">{{ data_usage }}</div>
                  <h3>Data Usage</h3>
                  <p><a href="javascript:;">More Info</a> </p>
                </div>
          </div>
      </div>
    </div>

{% endblock content %}

captive_portal/admin/api/templates/captive_portal/package_create.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Create Package</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="name" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.name.value != None %} value="{{ form.name.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.name.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.data_limit.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Data Limit</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="data_limit" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.data_limit.value != None %} value="{{ form.data_limit.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.data_limit.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.activation_days.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activation Days</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="activation_days" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.activation_days.value != None %} value="{{ form.activation_days.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.activation_days.errors }}</div>
                  </div>

                 <div class="item form-group {% if form.expiration_days.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Expiration Days</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="expiration_days" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.expiration_days.value != None %} value="{{ form.expiration_days.value }}" {% endif %}
                        />
                    </div>
                    <div class="alert">{{ form.expiration_days.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Create</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin/api/templates/captive_portal/package_edit.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Edit Package</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="name" value="{{ form.name.value }}" type="text" class="form-control col-md-7 col-xs-12" />
                    </div>
                    <div class="alert">{{ form.name.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.data_limit.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Data Limit</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="data_limit" value="{{ form.data_limit.value }}" type="text" class="form-control col-md-7 col-xs-12" />
                    </div>
                    <div class="alert">{{ form.data_limit.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.activation_days.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Activation Days</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="activation_days" value="{{ form.activation_days.value }}" type="text" class="form-control col-md-7 col-xs-12" />
                    </div>
                    <div class="alert">{{ form.activation_days.errors }}</div>
                  </div>

                 <div class="item form-group {% if form.expiration_days.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Expiration Days</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="expiration_days" value="{{ form.expiration_days.value }}" type="text" class="form-control col-md-7 col-xs-12" />
                    </div>
                    <div class="alert">{{ form.expiration_days.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Save</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin/api/templates/captive_portal/settings.html
{% extends 'base.html' %}

{% block head_css %}
    <style>
        label {
            text-align: left !important;
        }
    </style>
{% endblock head_css %}

{% block content %}

    <div>
      <div class="col-md-6 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Allowed Social Login</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                {% if social_login_formset|length > 0 %}
                    <form method="post" class="form-horizontal form-label-left">
                    {{ social_login_formset.management_form }}

                    {% csrf_token %}

                    {% for form in social_login_formset %}
                        {{ form.id }}
                        <div class="item form-group {% if form.is_active.errors %} bad {% endif %}">
                            <label class="control-label col-md-6 col-sm-6 col-xs-12">{{ form.name.value|title }}</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <label>
                                  <input name="{{ form.is_active.html_name }}" class="form-control js-switch" type="checkbox"
                                         {% if form.is_active.value != False %} checked="checked" {% endif %}
                                  />
                                </label>
                            </div>
                            <div style="margin-top: 10px;" class="alert pull-right">{{ form.is_active.errors }}</div>
                      </div>
                    {% endfor %}

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                        <input type="hidden" name="form" value="social-login-form" />
                      <button type="submit" class="btn btn-success">Save</button>
                    </div>
                  </div>

                </form>
                {% else %}
                    <p>No social provider added yet.</p>
                {% endif %}
              </div>
         </div>
      </div>


      <div class="col-md-6 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Wifi Login Timeout</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">
                    {% csrf_token %}

                  <div class="item form-group {% if wifi_timeout_form.login_timeout.errors %} bad {% endif %}">
                        <label class="control-label col-md-6 col-sm-6 col-xs-12">Login Timeout (minutes)</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                              <input name="login_timeout" class="form-control" type="text"
                                     {% if wifi_timeout_form.login_timeout.value != None %} value="{{ wifi_timeout_form.login_timeout.value }}" {% endif %}
                              />
                        </div>
                        <div style="margin-top: 10px;" class="alert">{{ wifi_timeout_form.login_timeout.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <input type="hidden" name="form" value="wifi-timeout-form" />
                      <button type="submit" class="btn btn-success">Save</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>
    </div>

{% endblock content %}

captive_portal/admin/api/templates/captive_portal/voucher_create.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Create Voucher</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="name" type="text" class="form-control col-md-7 col-xs-12"
                                {% if form.name.value != None %} value="{{ form.name.value }}" {% endif %}
                                 />
                    </div>
                    <div class="alert">{{ form.name.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.code.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Code</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="code" type="text" class="form-control col-md-7 col-xs-12"
                               {% if form.code.value != None %} value="{{ form.code.value }}" {% endif %}
                               />
                    </div>
                    <div class="alert">{{ form.code.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.package.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Package</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <select name="{{ form.package.name }}" class="form-control col-md-7 col-xs-12">
                        {% for choice in form.package.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <div class="alert">{{ form.package.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Create</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin/api/templates/captive_portal/voucher_edit.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <div class="col-md-12 col-xs-12">
         <div class="x_panel">
             <div class="x_title">
                <h2>Edit Voucher</h2>
                <div class="clearfix"></div>
              </div>
             <div class="x_content">
                <br>
                <form method="post" class="form-horizontal form-label-left">

                  {% csrf_token %}

                  <div class="item form-group {% if form.name.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="name" value="{{ form.name.value }}" type="text" class="form-control col-md-7 col-xs-12" />
                    </div>
                    <div class="alert">{{ form.name.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.code.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Code</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input name="code" value="{{ form.code.value }}" type="text" class="form-control col-md-7 col-xs-12" />
                    </div>
                    <div class="alert">{{ form.code.errors }}</div>
                  </div>

                  <div class="item form-group {% if form.package.errors %} bad {% endif %}">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Package</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <select name="{{ form.package.name }}" class="form-control col-md-7 col-xs-12">
                        {% for choice in form.package.field.choices %}
                            <option {% ifequal choice.0 form.package.value %} selected="selected" {% endifequal %} value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                    </div>
                    <div class="alert">{{ form.package.errors }}</div>
                  </div>

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                      <button type="submit" class="btn btn-success">Save</button>
                    </div>
                  </div>

                </form>
              </div>
         </div>
      </div>

    </div>

{% endblock content %}

captive_portal/admin/api/templates/captive_portal/voucher_list.html
{% extends 'base.html' %}

{% block content %}

   <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Vouchers</h2>

            {% if perms.VoucherCreate %}
                <a href="{% url 'captive_portal:voucher-create' %}" role="button" class="btn btn-info btn-xs pull-right">
                    Add Voucher
                </a>
            {% endif %}
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table  class="table jambo_table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Code</th>
                  <th>Package</th>
                  <th>Creation Date</th>
                  <th>Expiration Date</th>
                  <th>Data Limit</th>
                  <th>Status</th>
                  <th></th>
                </tr>
              </thead>


              <tbody>
                {% for voucher in vouchers %}
                    <tr>
                      <td>{{ voucher.name }}</td>
                      <td>{{ voucher.code }}</td>
                      <td>{{ voucher.package }}</td>
                      <td>{{ voucher.creation_date }}</td>
                      <td>{{ voucher.expiration_date }}</td>
                      <td>{{ voucher.data_limit }}</td>
                      <td>{{ voucher.status }}</td>
                      <td>

                          {% if perms.VoucherEdit %}
                            <a href="{% url 'captive_portal:voucher-edit' voucher.id %}" title="Edit"><i class="fa fa-edit"></i> </a>
                          {% endif %}&emsp;

                          {% if perms.VoucherDelete %}
                              <a title="Delete" class="delete-voucher" ><i class="fa fa-trash"></i></a>
                              <form style="display: none;" method="post" action="{% url 'captive_portal:voucher-delete' voucher.id %}">
                                {% csrf_token %}
                              </form>
                          {% endif %}
                      </td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Packages</h2>

            {% if perms.PackageCreate %}
                <a href="{% url 'captive_portal:package-create' %}" role="button" class="btn btn-info btn-xs pull-right">
                    Add Package
                </a>
            {% endif %}

            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <table  class="table jambo_table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Data Limit</th>
                  <th>Activation Days</th>
                  <th>Expiration Days</th>
                  <th></th>
                </tr>
              </thead>


              <tbody>
                {% for package in packages %}
                    <tr>
                      <td>{{ package.name }}</td>
                      <td>{{ package.data_limit }}</td>
                      <td>{{ package.activation_days }}</td>
                      <td>{{ package.expiration_days }}</td>
                      <td>

                          {% if perms.PackageEdit %}
                            <a href="{% url 'captive_portal:package-edit' package.id %}" title="Edit"><i class="fa fa-edit"></i> </a>
                          {% endif %}&emsp;

                          {% if perms.PackageDelete %}
                              <a title="Delete" class="delete-package" ><i class="fa fa-trash"></i></a>
                              <form style="display: none;" method="post" action="{% url 'captive_portal:package-delete' package.id %}">
                                {% csrf_token %}
                              </form>
                          {% endif %}
                      </td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>
   </div>

{% endblock content %}


{% block extra_js %}
    <script>
        $(document).ready(function(){
            $('a.delete-package, a.delete-voucher').on('click', function(){
                if (confirm('Do you really want to delete?')){
                    $(this).next().submit();
                }

            });
        });
    </script>
{% endblock extra_js %}